name: CelesteParkour
version: '${project.version}'
main: com.github.gameoholic.celesteparkour.celesteparkour.CelesteParkour
api-version: 1.19
authors: [ Gameoholic ]
description: Celeste-like parkour plugin developed for the MC Wipeout event
commands:
  parkourenable:
    description: Starts switching between block1 and block2 periodically. Use when testing/running the course.
    usage: /parkourenable
  parkourdisable:
    description: Stops the parkour block switching mechanism. Use when building the course.
    usage: /parkourdisable
  parkourinterval:
    description: Sets the interval in ticks for switching the blocks. Prints current interval if no interval was provided.
    usage: /parkourinterval or /parkourinterval <interval>
  parkourwarndelay:
    description: Sets the time in ticks to wait before switching to the warning block. Prints current interval if no interval was provided.
    usage: /parkourwarndelay or /parkourwarndelay <interval>
  block1:
    description: Sets the first building block of the parkour course. Leave empty to view
    usage: /block1 <block_type>
  block2:
    description: Sets the second building block of the parkour course. Leave empty to view
    usage: /block2 <block_type>
  block3:
    description: Sets the warning building block of the parkour course. Leave empty to view
    usage: /block3 <block_type>
  parkourregion:
    description: Start editing a parkour region. Leave empty to view current region, 0 to cancel.
    usage: /parkourregion